name: ci-cd Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t wisecow:latest .
      - name: Push Docker image (optional)
        run: echo "Docker image pushed to registry"
      - name: Deploy to Kubernetes
        run: echo "Deploy updated image to cluster"
