apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow
  file:
    matchPaths:
      # Allow only necessary files
      - path: "/usr/share/fortune"
        action: Allow
      - path: "/usr/local/bin/cowsay"
        action: Allow
  process:
    matchPaths:
      # Allow only required binaries
      - path: "/usr/games/fortune"
        action: Allow
      - path: "/usr/local/bin/cowsay"
        action: Allow
